# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/constraints/Cora-Z7-Master.xdc

# Block Designs: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_axi_dma_0_0_1/system_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_dma_0_0 || ORIG_REF_NAME==system_axi_dma_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_axi_intc_0_0_1/system_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_intc_0_0 || ORIG_REF_NAME==system_axi_intc_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_axis_data_fifo_0_0_1/system_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_blk_mem_gen_0_0_1/system_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_blk_mem_gen_0_0 || ORIG_REF_NAME==system_blk_mem_gen_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_clk_wiz_25M_0_1/system_clk_wiz_25M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_25M_0 || ORIG_REF_NAME==system_clk_wiz_25M_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_data_lmb_bram_if_cntlr_1_0_1/system_data_lmb_bram_if_cntlr_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_lmb_bram_if_cntlr_1_0 || ORIG_REF_NAME==system_data_lmb_bram_if_cntlr_1_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_data_lmb_v10_1_0_1/system_data_lmb_v10_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_data_lmb_v10_1_0 || ORIG_REF_NAME==system_data_lmb_v10_1_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_dma_axi_bram_ctrl_1_0_1/system_dma_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dma_axi_bram_ctrl_1_0 || ORIG_REF_NAME==system_dma_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_dma_blk_mem_gen_1_0_1/system_dma_blk_mem_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dma_blk_mem_gen_1_0 || ORIG_REF_NAME==system_dma_blk_mem_gen_1_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_fifo_count_axi_gpio_0_0_1/system_fifo_count_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_fifo_count_axi_gpio_0_0 || ORIG_REF_NAME==system_fifo_count_axi_gpio_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_i2s_output_1_0_1/system_i2s_output_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_i2s_output_1_0 || ORIG_REF_NAME==system_i2s_output_1_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_ins_lmb_bram_if_cntlr_0_0_1/system_ins_lmb_bram_if_cntlr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ins_lmb_bram_if_cntlr_0_0 || ORIG_REF_NAME==system_ins_lmb_bram_if_cntlr_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_ins_lmb_v10_0_0_1/system_ins_lmb_v10_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ins_lmb_v10_0_0 || ORIG_REF_NAME==system_ins_lmb_v10_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_int_axi_gpio_0_0_1/system_int_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_int_axi_gpio_0_0 || ORIG_REF_NAME==system_int_axi_gpio_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_mb_axi_mem_interconnect_0_0_1/system_mb_axi_mem_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_axi_mem_interconnect_0_0 || ORIG_REF_NAME==system_mb_axi_mem_interconnect_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_mb_dma_axi_bram_ctrl_0_0_1/system_mb_dma_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mb_dma_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_mb_dma_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_microblaze_0_0_1/system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_proc_sys_reset_0_0_1/system_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0_0 || ORIG_REF_NAME==system_proc_sys_reset_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_processing_system7_0_0_1/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_ps7_0_axi_periph_0_1/system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_rst_ps7_0_100M_0_1/system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_xadc_wiz_0_0_1/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_xlconcat_2_0_1/system_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_2_0 || ORIG_REF_NAME==system_xlconcat_2_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_xlconstant_0_0_1/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_xlconstant_1_0_1/system_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_1_0 || ORIG_REF_NAME==system_xlconstant_1_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_xbar_1_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_xbar_0_1/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_FrankenCryptCore_0_0/system_FrankenCryptCore_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_FrankenCryptCore_0_0 || ORIG_REF_NAME==system_FrankenCryptCore_0_0} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: /home/heiko/Desktop/Hardware_Sandbox/2020-ectf-insecure-example_copy/pl/src/bd/system/system_ooc.xdc
